<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Common.targets" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniCon.PenumbraMeta\UniCon.PenumbraMeta.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
  </ItemGroup>
</Project>
